# Generated by Django 3.0.5 on 2020-04-15 14:48

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='media/house_images/%y/%m/%d'), size=None),
        ),
        migrations.AlterField(
            model_name='house',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.IntegerField(),
        ),
    ]
