# Generated by Django 3.0.5 on 2020-04-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_auto_20200415_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='images',
            field=models.ImageField(upload_to='media/house_images/%y/%m/%d'),
        ),
    ]
