# Generated by Django 3.0.5 on 2020-04-15 16:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_auto_20200415_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
