# Generated by Django 3.0.5 on 2020-04-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0011_auto_20200416_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='master_image',
            field=models.ImageField(upload_to='media/master_image/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='houseimages',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/house_images/%y/%m/%d'),
        ),
    ]
