# Generated by Django 3.0.5 on 2020-04-17 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0012_auto_20200416_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='location',
        ),
    ]
