# Generated by Django 3.0.5 on 2020-04-17 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0015_auto_20200417_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='location',
        ),
    ]
