# Generated by Django 3.0.5 on 2020-04-17 16:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0016_remove_house_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
