# Generated by Django 3.0.5 on 2020-04-17 17:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0018_auto_20200417_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326),
        ),
    ]
