# Generated by Django 3.0.5 on 2020-05-27 09:05

from django.db import migrations
import houses.models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0021_auto_20200424_1738'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', houses.models.CustomUserManager()),
            ],
        ),
    ]
