# Generated by Django 3.0.5 on 2020-05-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0022_auto_20200527_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
