# Generated by Django 3.0.5 on 2020-05-27 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0024_auto_20200527_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_picture',
            new_name='picture',
        ),
    ]
